### ISSUE TITLE
Layout broken when upgrading from 1.2.3 to 1.3.0

### ISSUE THREAD

**Issue by Kohdepitcher** [SCENEE/FloatingPanel#87] opened 2018-12-17 11:24 UTC
In the 1.2 version of the framework, the floating panel in my app that is used as a pull up calculator worked well but after upgrading to 1.3, the floating panel refuses to even display at all. The strange part is that when using the user interface inspector in Xcode I can see that the floating panel is there and is the same height as my home VC. You can see the working version and non-working version below...

working collapsed state
![img_0977](https://user-images.githubusercontent.com/15321325/50083546-e8984800-023f-11e9-96ad-48ff1f1f1c6d.png)

working full height state
![img_0993](https://user-images.githubusercontent.com/15321325/50083560-f3eb7380-023f-11e9-8abe-c136b2429ea3.png)

not even displaying in 1.3
![img_0995](https://user-images.githubusercontent.com/15321325/50083604-0a91ca80-0240-11e9-87f9-b7ad410a762a.png)

The strange part is I can get it to show up by setting the initial position as .full but it doesn't render correctly as only the handle of the floating panel shows up as well as the home VC being darkened...
![img_0996](https://user-images.githubusercontent.com/15321325/50083734-5f354580-0240-11e9-9b5e-139c3db37504.png)

Another weird issue is that unlike 1.2, 1.3 doesn't actually show the whole of my calculator VC on screen, its like its ignoring the safe area again like the other issue I had in 1.1. you can see that here
What it should look like....
![img_0993](https://user-images.githubusercontent.com/15321325/50083874-d8349d00-0240-11e9-9c39-fe286a68f181.png)

what it looks like now
![img_0997](https://user-images.githubusercontent.com/15321325/50083885-e682b900-0240-11e9-8814-0fd9fac5077b.png)

I've tried for 3-4 hours to get it to work, the only thing that got close to what it used to look like on 1.2 was to use `self.present(floatingPanel, animated: true, completion: nil)` as suggested by you in the 1.3 branch which allowed the .tip and .full custom insets to work correctly. Unfortunately, this doesn't allow the collection view in the background to be panned until the floating panel is popped or dismissed.
You can see that here...
![img_0998](https://user-images.githubusercontent.com/15321325/50084117-a07a2500-0241-11e9-9745-0603b4bbb392.png)

This is the only code that I am using..

Inside view did load
```
` //setting calculatorVC the calculator class
        let storyboard = UIStoryboard(name: "Features", bundle: nil)
        let calculatorVC = storyboard.instantiateViewController(withIdentifier: "calculator") as! CalculatorViewController
        
        //set the delegate for the calculator
        calculatorVC.calculatorDelegate = self
        
        //set up floating panel
        floatingPanel.delegate = self
        
        floatingPanel.isRemovalInteractionEnabled = false
        
        floatingPanel.set(contentViewController: calculatorVC)

        
        floatingPanel.surfaceView.cornerRadius = 12.0
        floatingPanel.surfaceView.borderColor = UIColor.black
        floatingPanel.surfaceView.borderWidth = 0.5
        floatingPanel.surfaceView.backgroundColor = darkThemeColors.tableViewCellColor
        floatingPanel.surfaceView.shadowHidden = false
        
        floatingPanel.addPanel(toParent: self, belowView: nil, animated: true)`
```

````
extension HomeViewController: FloatingPanelControllerDelegate {
    func floatingPanel(_ vc: FloatingPanelController, layoutFor newCollection: UITraitCollection) -> FloatingPanelLayout? {
        return calculatorFloatingPanelLayout()
    }

}

class calculatorFloatingPanelLayout: FloatingPanelLayout {
    var initialPosition: FloatingPanelPosition {
        return .tip
    }

    var supportedPositions: Set<FloatingPanelPosition> {
        return [.full, .tip]
    }

    public func prepareLayout(surfaceView: UIView, in view: UIView) -> [NSLayoutConstraint] {

        if UIDevice.current.userInterfaceIdiom == .pad {
            
            //iPad layout
            if #available(iOS 11.0, *) {
                return [
                    surfaceView.leftAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leftAnchor, constant: 20.0),
                    surfaceView.rightAnchor.constraint(equalTo: view.safeAreaLayoutGuide.rightAnchor, constant: -20.0)
                ]
            } else {
                return [
                    surfaceView.leftAnchor.constraint(equalTo: view.leftAnchor, constant: 20.0),
                    surfaceView.rightAnchor.constraint(equalTo: view.rightAnchor, constant: -20.0),
                ]
            }
        }
        
        
        //iPhone layout
        else {
            return [
                surfaceView.leftAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leftAnchor, constant: 0.0),
                surfaceView.rightAnchor.constraint(equalTo: view.safeAreaLayoutGuide.rightAnchor, constant: 0.0)
            ]
        }
        return [NSLayoutConstraint]()
    }
    
    func insetFor(position: FloatingPanelPosition) -> CGFloat? {
        switch position {
        case .full: return 16.0
        case .tip: return 90.0
        default: return nil
        }
    }
    
}`

```
Im sorry if its a simple mistake but it is completely escaping me on what I am doing wrong. Keep up the awesome work on this library.

**Comment by Kohdepitcher** [comment] 2018-12-17 11:39
Also the use of a search controller in the navigation bar also seems to throw off the bottom safe area on the floating panel

**Comment by SCENEE** [comment] 2018-12-18 10:35
If you have a time, could you please try `improve-samples-app` branch?

**Comment by Kohdepitcher** [comment] 2018-12-20 13:16
Ok I have tried the improve-samples-app branch and the issue is still present. Another issue that is affecting both improve-samples-app branch and the master 1.3 branch is that if the parent VC has a search controller in the navigation bar, the bottom safe area of the floating panel is pushed below the screen. when I removed the search controller, only the top part of the floating panel, the height of the handle, shows up on the bottom of the screen

**Comment by SCENEE** [comment] 2018-12-21 02:15
I found a suspicious problem of Auto Layout constraints to SafeArea.Top with a translucent navigation bar. 

I struggled with it over a day but I can't figure out the reason now... However I found the issue can be resolved by replacing the constraints to **SafeArea.Top** with ones to **Superview.Top**. I think the change doesn't matter from characteristics of the UI, it's not best though.

I updated `improve-samples-app` branch(_NOTE: forced update_) and then I added `preconditionFailure` for SafeArea.Top with with a translucent navigation bar.
https://github.com/SCENEE/FloatingPanel/pull/86/files#diff-9010b8645e15999bbcccd463b07b21bfR264

What do you think of it?

**Comment by Kohdepitcher** [comment] 2018-12-27 11:08
Sorry I've just been on Christmas holidays, so far I have tried the new update to the improve-samples-app but the issue still exists. But after reconsidering the workflow of my app, I'm gonna put the calculator somewhere else without the floating panel. But I will use the floating panel for another idea I've got. Really great framework even though there's minor hiccups. Keep up the awesome work.

**Comment by SCENEE** [comment] 2018-12-30 01:04
I'm so sorry that I couldn't help you and your beautiful app. I've released v1.3.1 today. I hope this issue would be fixed. I really appreciate your help. I always welcome any contributions. Thank you so much!

**Comment by AlexLamond** [comment] 2019-03-15 20:12
➕1️⃣ I can reproduce this issue on the latest version, downgrading to 1.2.3 via CocaPods and the issue is gone

**Comment by SCENEE** [comment] 2019-03-26 13:36
This issue might be fixed by PR #168. It will be released in v1.4.1.

**Comment by SCENEE** [comment] 2019-04-04 03:06
I've released v1.4.1 today. Could you please try it? Thanks.

**Comment by SCENEE** [comment] 2019-04-10 08:03
Thanks, @AlexLamond. I understand your issue now. I will investigate it.

**Comment by SCENEE** [comment] 2019-06-15 05:32
@AlexLamond.,
The view hierarchy was changed between 1.2.3 to 1.3.0 so that the issue happens. The change might affect the safeAreaInsets update by the iOS layout system on the FloatingPanelController in your app. 

By the way, You're able to resolve this issue with `contentInsetAdjustmentBehavior = never` and manually update a content inset of your content view

It's so difficult for me to fix this issue as long as I can't repro this issue. So If you give me a sample code(it's ok to send it to me by email), that is much helpful.

**Comment by SCENEE** [comment] 2019-07-26 14:30
v1.6.3 has a bugfix for the SafeArea. Additionally `change-safe-area-reference` branch has a possible-fix for this safe area issue. I'm so glad if you try both of them.

**Comment by SCENEE** [comment] 2020-12-05 02:44
If anyone could reproduce this issue on v2, please reopen this.

**Closed by SCENEE** 2020-12-05 02:44 UTC
