### ISSUE TITLE
contentViewController is masked with a gray layer in iOS 10 and iOS 11 

### ISSUE THREAD

**Issue by ugenlik** [SCENEE/FloatingPanel#109] opened 2019-01-16 19:49 UTC
I set the floating panel as follow

```
        // Initialize FloatingPanelController
        floatingPanel = FloatingPanelController()
        floatingPanel.delegate = self
        
        // Initialize FloatingPanelController and add the view
        floatingPanel.surfaceView.backgroundColor = UIColor(displayP3Red: 30.0/255.0, green: 30.0/255.0, blue: 30.0/255.0, alpha: 1.0)
        floatingPanel.surfaceView.cornerRadius = 12.0
        floatingPanel.surfaceView.shadowHidden = true
        floatingPanel.surfaceView.borderWidth = 1.0 / traitCollection.displayScale
        floatingPanel.surfaceView.borderColor = UIColor.black.withAlphaComponent(0.2)
        
        
        appointmentsRoot = storyboard?.instantiateViewController(withIdentifier: "AppointmentsRootVC") as? AppointmentsRootVC
        
        // Set a content view controller
        floatingPanel.set(contentViewController: appointmentsRoot)
        floatingPanel.track(scrollView: appointmentsRoot.tableView)
        
        floatingPanel.addPanel(toParent: self, belowView: self.tabBarController?.view, animated: false)
```

and it works fine in iOS 12 

![simulator screen shot - iphone 8 - 2019-01-16 at 14 40 35](https://user-images.githubusercontent.com/1995917/51274644-adec1180-199d-11e9-9349-c98f286ecb6c.png)

but in iOS 10 and iOS 11  contentviewcontoller has a gray layer on it. 

![img_5424](https://user-images.githubusercontent.com/1995917/51274693-d247ee00-199d-11e9-9b5a-56e5c0c45a9b.png)

any idea how to resolve this>

**Comment by SCENEE** [comment] 2019-03-05 22:53
It might be fixed on v1.4.0 because it changed the implementation of FloatingPanelSurfaceView.

**Comment by ugenlik** [comment] 2019-03-18 16:05
@SCENEE  I finally figured out that this line caused the issue 
`floatingPanel.surfaceView.borderColor` 

so in iOS 10- 11 setting to clear solves the issue.

`floatingPanel.surfaceView.borderColor = UIColor.clear`


````
        if #available(iOS 12.0, *) {
            floatingPanel.surfaceView.borderColor =  UIColor.black.withAlphaComponent(0.2)
        }
        else
        {
            floatingPanel.surfaceView.borderColor = UIColor.clear
        }
```

**Comment by SCENEE** [comment] 2019-03-19 01:06
Great work! 🎉 ✨  I'm going to investigate `surfaceView.borderColor` effect 😉

**Comment by SCENEE** [comment] 2019-03-29 12:55
The root cause might be that `1.0 / traitCollection.displayScale` is large on iOS 10/11. 
And it doesn't seems be this library's issue because `floatingPanel.surfaceView.borderColor = UIColor.clear` is equal to `floatingPanel.surfaceView.contentView?.layer.borderColor = UIColor.clear.cgColor`

**Closed** 2019-04-17 10:21 UTC
