### ISSUE TITLE
Issue with safe area ignored in the floating panel’s controller when navigation bar translucency is turned off

### ISSUE THREAD

**Issue by Kohdepitcher** [SCENEE/FloatingPanel#26] opened 2018-11-01 13:15 UTC
After looking through the sample project and seeing how content in the drawer is correctly pinned to the bottom of the safe area thus preventing any content from being off screen. How ever, when trying to make the floating panel work with an existing view controller in my own project, any views that are pinned to the bottom safe area are cut off. With further testing by creating a test project, the issue doesn't occur as seen in the following screen shot.
![img_0735](https://user-images.githubusercontent.com/15321325/47853799-9df77380-de2b-11e8-849c-89b5416a4ead.PNG)

But the same pink rectangle is cut off in my own project..
![img_0736](https://user-images.githubusercontent.com/15321325/47853800-9df77380-de2b-11e8-86d0-7d162464b2b4.PNG)

Not entirely sure if its a project issue with mine or some code that you have used in the sample project.

**Comment by Kohdepitcher** [comment] 2018-11-01 14:33
After some more trial an error, the issue seems to be with UINavigationController. After I replaced my original embedded navigation controller with a new one, the issue was solved but now if I make my navigation controller's navigation bar translucent disabled, the issue comes back. It seems that changing the translucency of the navigation bar stops the safe area working correctly for the floating drawer.

**Comment by Kohdepitcher** [comment] 2018-11-04 11:47
I've tried to use the this new branch, fix-navigation-bar-problem, in my Podfile but it hasn't fixed this issue. I've gone through the floating panel files in my project and I have noticed that some changes that you have made in the floating panel layout file is not in my floating panel layout file in my app.  It's as if CocoaPods is ignoring your latest push to the fix-navigation-bar-problem branch. Ive also tried to replace the floating panel files in my project with the source files in this branch from GitHub and that didn't work as well. I'll try it with another branch that is newer and I'll let you know how it goes.

**Comment by SCENEE** [comment] 2018-11-05 00:01
Could you try `pod cache clean FloatingPanel --all && pod deintegrate && pod install --repo-update`?

**Comment by Kohdepitcher** [comment] 2018-11-05 03:21
Same issue again, I've run that command, tried with translucency off and it still isn't working. its still got the same issue with changes in the branch not showing up in my floating panel files. Strange

**Comment by SCENEE** [comment] 2018-11-05 04:53
Hmmm, what's happen on you... I can get the correct code by this Podfile.
```
platform :ios, '10.0'

target 'FloatingPanelSandbox' do
  use_frameworks!
  pod 'FloatingPanel', :git => "https://github.com/SCENEE/FloatingPanel.git", :branch => "fix-navigation-bar-problem"
end
```

**Comment by SCENEE** [comment] 2018-11-05 09:34
It looks no problem. How can I help you...? 🤔

**Comment by Kohdepitcher** [comment] 2018-11-05 09:35
Well I don't know what's going on, but I just downloaded the sample project from this branch. it has the all the code from the latest push and I can confirm the translucency issue is fixed in the sample project.

**Comment by SCENEE** [comment] 2018-11-06 01:10
Thanks for your confirmation, @Kohdepitcher! I merged 'fix-navigation-bar-problem' branch for convenience.
There might be a CocoPods issue, but we're not clear about the cause. If you find something wrong of this library, please let me know 😀

**Closed** 2018-11-06 01:10 UTC
