### ISSUE TITLE
Backdrop view isn't masked

### ISSUE THREAD

**Issue by futuretap** [SCENEE/FloatingPanel#42] opened 2018-11-10 00:13 UTC
When using a `UIVisualEffectView` as the background of the content view, the background is displayed in a blurred style. Now when the panel is moved to the `.full` position, the `backdropView` is faded in, e.g. with 30% black. Since the `backdropView` doesn't mask the `surfaceView`, the blurred background gets slightly darker.

Would be great to fully replicate the Maps.app behavior where only the backdrop view is faded in but the panel background color is unchanged.

The issue can best be observed in the Maps sample app.

**Comment by futuretap** [comment] 2018-11-13 15:36
Maybe [this technique](https://briancoyner.github.io/2017/05/15/uivisualeffectview-with-drop-shadow.html) could be used to achieve a backdrop view that doesn't affect the `UIVisualEffectView`.

**Comment by SCENEE** [comment] 2018-11-15 15:24
I confirmed this issue was fixed by you on PR #51. Thanks again.

**Comment by futuretap** [comment] 2018-11-15 16:07
No, these are actually two separate things. The backdropView is placed in a sibling view of the surfaceView and the UIVisualEffectView still captures the dark background. You can reproduce this in the Maps sample app by replacing:

```
    public func backdropAlphaFor(position: FloatingPanelPosition) -> CGFloat {
		switch position {
		case .full: return 0.5
		default: return 0.0
		}
    }
```

As you can see, the blurred part is significantly darker in the .full position:

<img width="597" alt="backdrop-issue" src="https://user-images.githubusercontent.com/110374/48565461-e36e7300-e8f8-11e8-985b-edfca1ea9431.png">

**Comment by futuretap** [comment] 2018-11-16 10:58
Can you please reopen this? It's not yet solved.

**Comment by SCENEE** [comment] 2018-11-17 00:38
It's not possible by this library side.

Because a content VC of FloatingPanelController is variable. Not only the corner radius value, the whole shape can be changed by a user. 

So it's not possible that FloatingPanelController take care of a special condition of a content VC like the above. If it takes care of it, FloatingPanelController could produce layout bugs.

However, you can handle `FloatingPanelController.backdropView` with `FloatingPanelControllerDelegate` or `FloatingPanelController.panGestureRecognizer`. 

It means it's possible to customize the backdrop view as you like. For example,  always hide backdrop always , change the color, etc.

As a result, you will achieve what you expected by yourself.

**Closed** 2019-04-20 06:54 UTC
